version: 2.1

orbs:
  architect: giantswarm/architect@0.11.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-g8s-cert-manager-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "g8s-cert-manager"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
