version: 2.1

orbs:
  architect: giantswarm/architect@0.11.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-g8s-cert-manager-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "g8s-cert-manager"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-g8s-cert-manager-to-aws-app-collection
          app_name: "g8s-cert-manager"
          app_namespace: "kube-system"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-g8s-cert-manager-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-g8s-cert-manager-to-azure-app-collection
          app_name: "g8s-cert-manager"
          app_namespace: "kube-system"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-g8s-cert-manager-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to kvm installations (only tags)
      - architect/push-to-app-collection:
          name: push-g8s-cert-manager-to-kvm-app-collection
          app_name: "g8s-cert-manager"
          app_namespace: "kube-system"
          app_collection_repo: "kvm-app-collection"
          unique: "true"
          requires:
            - push-g8s-cert-manager-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
