# Hacker note. Bare pod to create clusterissuer CR with letsencrypt configuration.
# Workaround for https://github.com/kubernetes/helm/issues/2994
apiVersion: v1
kind: Pod
metadata:
  name: cert-manager-add-clusterissuer-{{ .Files.Get "misc/letsencrypt.yaml" | sha256sum }}
  namespace: kube-system
spec:
  serviceAccountName: cert-manager
  restartPolicy: OnFailure
  containers:
  - image: quay.io/giantswarm/docker-kubectl:e777d4eaf369d4dabc393c5da42121c2a725ea6a
    args:
      - apply
      - -f
      - /data/clusterissuer
    name: kubectl
    volumeMounts:
    - name: cert-manager-add-clusterissuer
      mountPath: /data/
  volumes:
  - configMap:
      name: cert-manager-add-clusterissuer
    name: cert-manager-add-clusterissuer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-add-clusterissuer
  namespace: kube-system
data:
  clusterissuer: |
{{ .Files.Get "misc/letsencrypt.yaml" | indent 4 }}
