apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
  namespace: kube-system
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller:v0.2.5
          imagePullPolicy: IfNotPresent
          args:
          # This is currently commented out until the 0.3 release of
          # cert-manager, as it results in a breaking change (users will need
          # to move credentials/acme private keys from kube-system into the
          # same namespace cert-manager is deployed into.
          # - --cluster-resource-namespace=$(POD_NAMESPACE)
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
        - name: ingress-shim
          image: quay.io/jetstack/cert-manager-ingress-shim:v0.2.5
          imagePullPolicy: IfNotPresent
          args:
          - --default-issuer-name=letsencrypt
          - --default-issuer-kind=ClusterIssuer
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
